### PR TITLE
Fix hanging tests

### LINKED ISSUE #30: Tests hang both locally and in CI

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Resolves #30.

Some tests were failing because the default transport _http_json_ tries to publish spans to public LightStep satelillites but does not provide a valid access token so timeout / fail.

This change introduces a `createTestTracer` function in **BaseLightStepTest** that creates a tracer with flush disabled.

NOTE: InitializationTests still use a custom tracer, but still disables flushing.

### CODE REVIEW

File: test/BaseLightStepTest.php [hunk 1]
```diff
@@ -8,6 +8,14 @@
  */
 abstract class BaseLightStepTest extends PHPUnit_Framework_TestCase
 {
+    protected function createTestTracer($component_name, $access_token) {
+        $opts = [
+            "debug_disable_flush" => "true"
```
Comment (iredelmeier) [inline test/BaseLightStepTest.php]: Should this instead be `TRUE`, as it is [here](https://github.com/lightstep/lightstep-tracer-php/blob/453e8b8e203476b2491289695bf5d961096fc44e/test/RuntimeTest.php#L7)?

(Excuse my extreme PHP ignorance!)

**Review by iredelmeier — APPROVED** [review]

File: test/BaseLightStepTest.php (hunk 1 above)
Comment (MikeGoldsmith) [reply test/BaseLightStepTest.php]: They all evaluate to the same, but happy to align for consistency.
